/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAL.KlientiRepository;
import DAL.ProduktiRepository;
import DAL.TerapiaRepository;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author dfz
 */
public class Dashboard extends javax.swing.JInternalFrame {
    
    KlientiRepository kr = new KlientiRepository();
    
    ProduktiRepository pr = new ProduktiRepository();
    
    TerapiaRepository tr = new TerapiaRepository();
    
  
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        stats();
    }

    public void stats() {
            klienteRegjistruar.setText(kr.numeroKlientat() + "");
            produkteRegjistruar.setText(pr.numeroProduktet() + "");
            terapi.setText(tr.numeroTerapite() + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        terapi = new javax.swing.JTextField();
        klienteRegjistruar = new javax.swing.JTextField();
        produkteRegjistruar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        terapi.setBackground(new java.awt.Color(0, 0, 0));
        terapi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        terapi.setForeground(new java.awt.Color(255, 255, 255));
        terapi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        terapi.setBorder(null);
        jPanel1.add(terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 70, 40));

        klienteRegjistruar.setEditable(false);
        klienteRegjistruar.setBackground(new java.awt.Color(255, 255, 255));
        klienteRegjistruar.setFont(new java.awt.Font("Calibri", 0, 72)); // NOI18N
        klienteRegjistruar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        klienteRegjistruar.setBorder(null);
        jPanel1.add(klienteRegjistruar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 90, 70));

        produkteRegjistruar.setEditable(false);
        produkteRegjistruar.setBackground(new java.awt.Color(255, 255, 255));
        produkteRegjistruar.setFont(new java.awt.Font("Calibri", 0, 72)); // NOI18N
        produkteRegjistruar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        produkteRegjistruar.setBorder(null);
        jPanel1.add(produkteRegjistruar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 90, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produkter.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/klienter.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 210, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/terapi.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 360, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField klienteRegjistruar;
    private javax.swing.JTextField produkteRegjistruar;
    private javax.swing.JTextField terapi;
    // End of variables declaration//GEN-END:variables
}
