/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import static java.awt.Toolkit.getDefaultToolkit;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author dfz
 */
public class Home extends javax.swing.JFrame {

    RegjistroKlientin rk;
    RegjistroProduktin rp;
    RegjistroFurnizuesin rf;
    RegjistroStafin rs;
    RegjistroPerdoruesin rp1;
    ListaKlienteve lk;
    ListaProdukteve lp;
    MenaxhoKomunat mk;
    MenaxhoLlojinEProduktit mlp;
    MenaxhoTipinEStafit mts;
    
    ShtoProduktetEFurnizuesit spf;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height - 41);
        instancat();
        dashboard();
    }

    public void instancat() {
        rk = new RegjistroKlientin();
        rp = new RegjistroProduktin();
        rf = new RegjistroFurnizuesin();
        rs = new RegjistroStafin();
        rp1 = new RegjistroPerdoruesin();
        lk = new ListaKlienteve();
        lp = new ListaProdukteve();
        mk = new MenaxhoKomunat();
        
        spf = new ShtoProduktetEFurnizuesit();
        mlp = new MenaxhoLlojinEProduktit();
        mts = new MenaxhoTipinEStafit();

        primaryWindow.add(rk);
        primaryWindow.add(rp);
        primaryWindow.add(rf);
        primaryWindow.add(rs);
        primaryWindow.add(rp1);
        primaryWindow.add(lk);
        primaryWindow.add(lp);
        primaryWindow.add(mk);
        
        primaryWindow.add(spf);
        primaryWindow.add(mlp);
        primaryWindow.add(mts);
        // primaryWindow.add(d);

    }

    public void mbyll() {
        rk.setVisible(false);
        rp.setVisible(false);
        rf.setVisible(false);
        rs.setVisible(false);
        rp1.setVisible(false);
        lk.setVisible(false);
        lp.setVisible(false);
        mk.setVisible(false);
        
        spf.setVisible(false);
        // d.setVisible(false);
        mlp.setVisible(false);
        mts.setVisible(false);

    }

    

    

    public void highlights() {
        resetColor(btn_first);
        resetColor(btn_second);
        resetColor(btn_third);
        resetColor(btn_fourth);
        resetColor(btn_fifth);
        resetColor(btn_sixth);
        resetColor(btn_seventh);
        resetColor(btn_eighth);
        resetColor(btn_ninth);
        resetColor(btn_tenth);
        wl1.setOpaque(false);
        wl2.setOpaque(false);
        wl3.setOpaque(false);
        wl4.setOpaque(false);
        wl5.setOpaque(false);
        wl6.setOpaque(false);
        wl7.setOpaque(false);
        wl8.setOpaque(false);
        wl9.setOpaque(false);
        wl10.setOpaque(false);
    }

    public void dashboard() {
        Dashboard d = new Dashboard();
        primaryWindow.add(d);
        d.setVisible(true);
        d.stats();
        
        BasicInternalFrameUI bi;
        bi = (BasicInternalFrameUI) d.getUI();
        bi.setNorthPane(null);
        highlights();
        mbyll();

    }
    
    public void listaK(){
        ListaKlienteve lk = new ListaKlienteve();
        primaryWindow.add(lk);
        lk.setVisible(true);
        BasicInternalFrameUI bi;
        bi = (BasicInternalFrameUI) lk.getUI();
        bi.setNorthPane(null);        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        topbar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sidep = new javax.swing.JPanel();
        dropd1 = new javax.swing.JLabel();
        btn_third = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        wl3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_second = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        wl2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dropd2 = new javax.swing.JLabel();
        btn_fourth = new javax.swing.JPanel();
        icon5 = new javax.swing.JLabel();
        wl4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_fifth = new javax.swing.JPanel();
        icon4 = new javax.swing.JLabel();
        wl5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_sixth = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        wl6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btn_tenth = new javax.swing.JPanel();
        icon9 = new javax.swing.JLabel();
        wl10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        accicon = new javax.swing.JLabel();
        kycur = new javax.swing.JTextField();
        btn_first = new javax.swing.JPanel();
        icon10 = new javax.swing.JLabel();
        wl1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dropd3 = new javax.swing.JLabel();
        btn_seventh = new javax.swing.JPanel();
        icon11 = new javax.swing.JLabel();
        wl7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_eighth = new javax.swing.JPanel();
        icon12 = new javax.swing.JLabel();
        wl8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        dropd4 = new javax.swing.JLabel();
        btn_ninth = new javax.swing.JPanel();
        icon13 = new javax.swing.JLabel();
        wl9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        primaryWindow = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        parent.setBackground(new java.awt.Color(255, 255, 255));
        parent.setForeground(new java.awt.Color(255, 255, 255));
        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topbar.setBackground(new java.awt.Color(3, 165, 50));
        topbar.setForeground(new java.awt.Color(255, 153, 102));
        topbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarMouseDragged(evt);
            }
        });
        topbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarMousePressed(evt);
            }
        });
        topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closew.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        topbar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizew.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        topbar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, -1, 40));

        parent.add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 40));

        sidep.setBackground(new java.awt.Color(3, 165, 50));
        sidep.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidepMouseDragged(evt);
            }
        });
        sidep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidepMousePressed(evt);
            }
        });
        sidep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropd1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dropd1.setForeground(new java.awt.Color(204, 204, 204));
        dropd1.setText("KLIENT");
        sidep.add(dropd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 104, -1));

        btn_third.setBackground(new java.awt.Color(3, 165, 50));
        btn_third.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thirdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_thirdMousePressed(evt);
            }
        });
        btn_third.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_third.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl3.setBackground(new java.awt.Color(255, 255, 255));
        wl3.setOpaque(false);
        wl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_third.add(wl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Regjistro produktin");
        btn_third.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 140, 26));

        sidep.add(btn_third, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 208, -1));

        btn_second.setBackground(new java.awt.Color(3, 165, 50));
        btn_second.setEnabled(false);
        btn_second.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_secondMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_secondMousePressed(evt);
            }
        });
        btn_second.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_second.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl2.setBackground(new java.awt.Color(255, 255, 255));
        wl2.setOpaque(false);
        wl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_second.add(wl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista e klienteve");
        btn_second.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, -1, 26));

        sidep.add(btn_second, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 208, -1));

        dropd2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dropd2.setForeground(new java.awt.Color(204, 204, 204));
        dropd2.setText("SHTO");
        sidep.add(dropd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        btn_fourth.setBackground(new java.awt.Color(3, 165, 50));
        btn_fourth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fourthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_fourthMousePressed(evt);
            }
        });
        btn_fourth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_fourth.add(icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl4.setBackground(new java.awt.Color(255, 255, 255));
        wl4.setOpaque(false);
        wl4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_fourth.add(wl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista e produkteve");
        btn_fourth.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 130, 26));

        sidep.add(btn_fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, -1));

        btn_fifth.setBackground(new java.awt.Color(3, 165, 50));
        btn_fifth.setEnabled(false);
        btn_fifth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fifthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_fifthMousePressed(evt);
            }
        });
        btn_fifth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_fifth.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl5.setBackground(new java.awt.Color(255, 255, 255));
        wl5.setOpaque(false);
        wl5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_fifth.add(wl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stafin");
        btn_fifth.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 110, 26));

        sidep.add(btn_fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, -1));

        btn_sixth.setBackground(new java.awt.Color(3, 165, 50));
        btn_sixth.setEnabled(false);
        btn_sixth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sixthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sixthMousePressed(evt);
            }
        });
        btn_sixth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_sixth.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl6.setBackground(new java.awt.Color(255, 255, 255));
        wl6.setOpaque(false);
        wl6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_sixth.add(wl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Furnizuesin");
        btn_sixth.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 96, 26));

        sidep.add(btn_sixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 208, -1));

        logout.setOpaque(false);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DIL");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Export_24px.png"))); // NOI18N

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );

        logoutLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel5});

        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        logoutLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel5});

        sidep.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 80, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small_logo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        sidep.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 40));

        btn_tenth.setBackground(new java.awt.Color(3, 165, 50));
        btn_tenth.setEnabled(false);
        btn_tenth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tenthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tenthMousePressed(evt);
            }
        });
        btn_tenth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_tenth.add(icon9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl10.setBackground(new java.awt.Color(255, 255, 255));
        wl10.setOpaque(false);
        wl10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_tenth.add(wl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel14.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Llojin e produktit");
        btn_tenth.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 120, 26));

        sidep.add(btn_tenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 208, -1));

        accicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Male_User_24px.png"))); // NOI18N
        sidep.add(accicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 30, 30));

        kycur.setEditable(false);
        kycur.setBackground(new java.awt.Color(3, 165, 50));
        kycur.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        kycur.setForeground(new java.awt.Color(255, 255, 255));
        kycur.setBorder(null);
        kycur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kycurActionPerformed(evt);
            }
        });
        sidep.add(kycur, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 106, 90, 20));

        btn_first.setBackground(new java.awt.Color(3, 165, 50));
        btn_first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_firstMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_firstMousePressed(evt);
            }
        });
        btn_first.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_first.add(icon10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl1.setBackground(new java.awt.Color(255, 255, 255));
        wl1.setOpaque(false);
        wl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_first.add(wl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel15.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Regjistro klientin");
        btn_first.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 98, 26));

        sidep.add(btn_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 208, -1));

        dropd3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dropd3.setForeground(new java.awt.Color(204, 204, 204));
        dropd3.setText("PRODUKT");
        sidep.add(dropd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        btn_seventh.setBackground(new java.awt.Color(3, 165, 50));
        btn_seventh.setEnabled(false);
        btn_seventh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seventhMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_seventhMousePressed(evt);
            }
        });
        btn_seventh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_seventh.add(icon11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl7.setBackground(new java.awt.Color(255, 255, 255));
        wl7.setOpaque(false);
        wl7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_seventh.add(wl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Perdoruesin");
        btn_seventh.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 96, 26));

        sidep.add(btn_seventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 208, -1));

        btn_eighth.setBackground(new java.awt.Color(3, 165, 50));
        btn_eighth.setEnabled(false);
        btn_eighth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eighthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eighthMousePressed(evt);
            }
        });
        btn_eighth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_eighth.add(icon12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl8.setBackground(new java.awt.Color(255, 255, 255));
        wl8.setOpaque(false);
        wl8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_eighth.add(wl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel17.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Komunen");
        btn_eighth.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 96, 26));

        sidep.add(btn_eighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 208, -1));

        dropd4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dropd4.setForeground(new java.awt.Color(204, 204, 204));
        dropd4.setText("MENAXHO");
        sidep.add(dropd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        btn_ninth.setBackground(new java.awt.Color(3, 165, 50));
        btn_ninth.setEnabled(false);
        btn_ninth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ninthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ninthMousePressed(evt);
            }
        });
        btn_ninth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N
        btn_ninth.add(icon13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 35, 38));

        wl9.setBackground(new java.awt.Color(255, 255, 255));
        wl9.setOpaque(false);
        wl9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_ninth.add(wl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, 38));

        jLabel18.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tipin e stafit");
        btn_ninth.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 120, 26));

        sidep.add(btn_ninth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 208, -1));

        parent.add(sidep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 750));

        primaryWindow.setEnabled(false);

        javax.swing.GroupLayout primaryWindowLayout = new javax.swing.GroupLayout(primaryWindow);
        primaryWindow.setLayout(primaryWindowLayout);
        primaryWindowLayout.setHorizontalGroup(
            primaryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        primaryWindowLayout.setVerticalGroup(
            primaryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        parent.add(primaryWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1160, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xy, xx;
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void sidepMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_sidepMouseDragged

    private void sidepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_sidepMousePressed


    private void btn_thirdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thirdMousePressed
        highlights();
        setColor(btn_third);
        wl3.setOpaque(true);
    }//GEN-LAST:event_btn_thirdMousePressed

    private void btn_secondMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_secondMousePressed
        highlights();
        setColor(btn_second);
        wl2.setOpaque(true);
    }//GEN-LAST:event_btn_secondMousePressed

    private void btn_fourthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fourthMousePressed
        highlights();
        setColor(btn_fourth);
        wl4.setOpaque(true);
    }//GEN-LAST:event_btn_fourthMousePressed

    private void btn_fifthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fifthMousePressed
        highlights();
        setColor(btn_fifth);
        wl5.setOpaque(true);
    }//GEN-LAST:event_btn_fifthMousePressed

    private void btn_sixthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sixthMousePressed
        highlights();
        setColor(btn_sixth);
        wl6.setOpaque(true);
    }//GEN-LAST:event_btn_sixthMousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void topbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_topbarMouseDragged

    private void topbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_topbarMousePressed

    private void btn_tenthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tenthMousePressed
        highlights();
        setColor(btn_tenth);
        wl10.setOpaque(true);
    }//GEN-LAST:event_btn_tenthMousePressed

    private void btn_thirdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thirdMouseClicked
        // TODO add your handling code here:
        if (rp.isVisible()) {
            return;
        } else {
            mbyll();

            rp.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) rp.getUI();
            bi.setNorthPane(null);
            rp.loadCombobox();
            rp.loadTable();
        }
    }//GEN-LAST:event_btn_thirdMouseClicked

    private void btn_secondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_secondMouseClicked
        // TODO add your handling code here:   
        if (lk.isVisible()) {
            return;
        } else {
            mbyll();

            lk.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) lk.getUI();
            bi.setNorthPane(null);
            lk.loadTable();
        }

    }//GEN-LAST:event_btn_secondMouseClicked

    private void kycurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kycurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kycurActionPerformed

    private void btn_fourthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fourthMouseClicked
        // TODO add your handling code here:
        if (lp.isVisible()) {
            return;
        } else {
            mbyll();

            lp.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) lp.getUI();
            bi.setNorthPane(null);
            lp.loadTable();
        }
    }//GEN-LAST:event_btn_fourthMouseClicked

    private void btn_firstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_firstMouseClicked
        // TODO add your handling code here:
        if (rk.isVisible()) {
            return;
        } else {
            mbyll();

            rk.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) rk.getUI();
            bi.setNorthPane(null);
        }
        rk.loadCombobox();
        rk.loadTable();


    }//GEN-LAST:event_btn_firstMouseClicked

    private void btn_firstMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_firstMousePressed
        highlights();
        setColor(btn_first);
        wl1.setOpaque(true);
    }//GEN-LAST:event_btn_firstMousePressed

    private void btn_seventhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seventhMousePressed
        // TODO add your handling code here:
        highlights();
        setColor(btn_seventh);
        wl7.setOpaque(true);
    }//GEN-LAST:event_btn_seventhMousePressed

    private void btn_eighthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eighthMousePressed
        // TODO add your handling code here:
        highlights();
        setColor(btn_eighth);
        wl8.setOpaque(true);
    }//GEN-LAST:event_btn_eighthMousePressed

    private void btn_ninthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ninthMousePressed
        // TODO add your handling code here:
        highlights();
        setColor(btn_ninth);
        wl9.setOpaque(true);
    }//GEN-LAST:event_btn_ninthMousePressed

    private void btn_fifthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fifthMouseClicked
        // TODO add your handling code here:
        if (rs.isVisible()) {
            return;
        } else {
            mbyll();

            rs.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) rs.getUI();
            bi.setNorthPane(null);
            rs.loadCombobox();
            rs.loadTable();
        }

    }//GEN-LAST:event_btn_fifthMouseClicked

    private void btn_sixthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sixthMouseClicked
        // TODO add your handling code here:
        if (rf.isVisible()) {
            return;
        } else {
            mbyll();

            rf.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) rf.getUI();
            bi.setNorthPane(null);
            rf.loadCombobox();
            rf.loadTable();
        }
    }//GEN-LAST:event_btn_sixthMouseClicked

    private void btn_seventhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seventhMouseClicked
        // TODO add your handling code here:
        if (rp1.isVisible()) {
            return;
        } else {
            mbyll();

            rp1.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) rp1.getUI();
            bi.setNorthPane(null);
            rp1.loadTable();
        }
    }//GEN-LAST:event_btn_seventhMouseClicked

    private void btn_eighthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eighthMouseClicked
        // TODO add your handling code here:
        if (mk.isVisible()) {
            return;
        } else {
            mbyll();

            mk.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) mk.getUI();
            bi.setNorthPane(null);
            mk.loadTable();
        }
    }//GEN-LAST:event_btn_eighthMouseClicked

    private void btn_ninthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ninthMouseClicked
        // TODO add your handling code here:
        if (mts.isVisible()) {
            return;
        } else {
            mbyll();

            mts.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) mts.getUI();
            bi.setNorthPane(null);
            mts.loadTable();
        }

    }//GEN-LAST:event_btn_ninthMouseClicked

    private void btn_tenthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tenthMouseClicked
        // TODO add your handling code here:
        if (mlp.isVisible()) {
            return;
        } else {
            mbyll();

            mlp.setVisible(true);
            BasicInternalFrameUI bi;
            bi = (BasicInternalFrameUI) mlp.getUI();
            bi.setNorthPane(null);
            mlp.loadTable();
        }
    }//GEN-LAST:event_btn_tenthMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        dashboard();
    }//GEN-LAST:event_logoMouseClicked

    void setColor(JPanel sideP) {
        sideP.setBackground(new Color(3, 175, 65));
    }

    void resetColor(JPanel sideP) {
        sideP.setBackground(new Color(3, 165, 50));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accicon;
    private javax.swing.JPanel btn_eighth;
    private javax.swing.JPanel btn_fifth;
    private javax.swing.JPanel btn_first;
    private javax.swing.JPanel btn_fourth;
    private javax.swing.JPanel btn_ninth;
    private javax.swing.JPanel btn_second;
    private javax.swing.JPanel btn_seventh;
    private javax.swing.JPanel btn_sixth;
    private javax.swing.JPanel btn_tenth;
    private javax.swing.JPanel btn_third;
    private javax.swing.JLabel dropd1;
    private javax.swing.JLabel dropd2;
    private javax.swing.JLabel dropd3;
    private javax.swing.JLabel dropd4;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon10;
    private javax.swing.JLabel icon11;
    private javax.swing.JLabel icon12;
    private javax.swing.JLabel icon13;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    protected javax.swing.JTextField kycur;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel parent;
    private javax.swing.JDesktopPane primaryWindow;
    private javax.swing.JPanel sidep;
    private javax.swing.JPanel topbar;
    private javax.swing.JPanel wl1;
    private javax.swing.JPanel wl10;
    private javax.swing.JPanel wl2;
    private javax.swing.JPanel wl3;
    private javax.swing.JPanel wl4;
    private javax.swing.JPanel wl5;
    private javax.swing.JPanel wl6;
    private javax.swing.JPanel wl7;
    private javax.swing.JPanel wl8;
    private javax.swing.JPanel wl9;
    // End of variables declaration//GEN-END:variables

}
