/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BLL.Klienti;
import BLL.Komuna;
import BLL.Terapia;

import DAL.FarmaciaException;
import DAL.KlientiInterface;
import DAL.KlientiRepository;
import DAL.KomunaInterface;
import DAL.KomunaRepository;
import DAL.TerapiaRepository;
import gui.models.KlientiTableModel;
import gui.models.KomunaComboboxModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ASUS
 */
public class RegjistroKlientin extends javax.swing.JInternalFrame {

    ButtonGroup group = new ButtonGroup();
    KlientiRepository kr = new KlientiRepository();

    TerapiaRepository tr = new TerapiaRepository();

    KomunaInterface kir = new KomunaRepository();
    KomunaComboboxModel kcm;

    KlientiTableModel ktm;

    TerapiaFinal tf = new TerapiaFinal();

    /**
     * Creates new form RegjistroKlientin
     */
    public RegjistroKlientin() {
        initComponents();
        group.add(femer);
        group.add(mashkull);
        loadTable();
        loadCombobox();
        tabelaSelectedIndexChange();
        label.setVisible(false);
    }

    public void loadCombobox() {
        try {
            List<Komuna> list = kir.findAll();
            kcm = new KomunaComboboxModel(list);
            komunaCB.setModel(kcm);
            komunaCB.repaint();

        } catch (FarmaciaException se) {
            JOptionPane.showMessageDialog(this, se.getMessage());

        }
    }

    public void loadTable() {
        List<Klienti> list = kr.findAll();
        ktm = new KlientiTableModel(list);
        tabela.setModel(ktm);
        ktm.fireTableDataChanged();

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Klienti k = ktm.getKlienti(selectedIndex);
                    emri.setText(k.getEmri() + "");
                    mbiemri.setText(k.getMbiemri() + "");
                    dataLindjes.setDate(k.getDataLindjes());
                    numriTelefonit.setText(k.getNrTelefonit());
                    rruga.setText(k.getEmriRruges());
                    numriDeres.setText(k.getNumriHyrjes() + "");
                    kati.setText(k.getKati() + "");
                    pershkrimi.setText(k.getPershkrimi());

                    if (k.getGjinia() == 'F') {
                        femer.setSelected(true);
                    } else {
                        mashkull.setSelected(true);
                    }

                    komunaCB.setSelectedItem(k.getKomunaID());
                    komunaCB.repaint();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        mbiemri = new javax.swing.JTextField();
        saveKlientiButton = new javax.swing.JButton();
        femer = new javax.swing.JRadioButton();
        mashkull = new javax.swing.JRadioButton();
        dataLindjes = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deleteKlientiButton = new javax.swing.JButton();
        numriTelefonit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clearKlientiButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rruga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numriDeres = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kati = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pershkrimi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emri = new javax.swing.JTextField();
        prapa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        komunaCB = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        shtoTerapine = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Mbiemri:");

        saveKlientiButton.setBackground(new java.awt.Color(16, 141, 25));
        saveKlientiButton.setForeground(new java.awt.Color(255, 255, 255));
        saveKlientiButton.setText("Ruaj");
        saveKlientiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveKlientiButtonActionPerformed(evt);
            }
        });

        femer.setText("Femer");
        femer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femerActionPerformed(evt);
            }
        });

        mashkull.setText("Mashkull");
        mashkull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mashkullActionPerformed(evt);
            }
        });

        jLabel5.setText("Data Lindjes:");

        jLabel6.setText("Gjinia:");

        jLabel7.setText("Numri Telefonit:");

        deleteKlientiButton.setBackground(new java.awt.Color(16, 141, 25));
        deleteKlientiButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteKlientiButton.setText("Fshij");
        deleteKlientiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteKlientiButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Komuna:");

        clearKlientiButton.setBackground(new java.awt.Color(16, 141, 25));
        clearKlientiButton.setForeground(new java.awt.Color(255, 255, 255));
        clearKlientiButton.setText("Pastro");
        clearKlientiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearKlientiButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Rruga:");

        jLabel10.setText("Numri:");

        jLabel11.setText("Kati:");

        jLabel12.setText("Përshkrimi:");

        jLabel13.setText("Emri:");

        emri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emriActionPerformed(evt);
            }
        });

        prapa.setBackground(new java.awt.Color(16, 141, 25));
        prapa.setForeground(new java.awt.Color(255, 255, 255));
        prapa.setText("Prapa");
        prapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prapaActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabela.setGridColor(new java.awt.Color(153, 153, 153));
        tabela.setOpaque(false);
        jScrollPane1.setViewportView(tabela);

        komunaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komunaCBActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        shtoTerapine.setBackground(new java.awt.Color(16, 141, 25));
        shtoTerapine.setForeground(new java.awt.Color(255, 255, 255));
        shtoTerapine.setText("Shto terapine");
        shtoTerapine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shtoTerapineActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setText("Terapia e klientit:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(saveKlientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearKlientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteKlientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(numriDeres, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mashkull, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(pershkrimi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(dataLindjes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(rruga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(komunaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(numriTelefonit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(kati, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(shtoTerapine, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(prapa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dataLindjes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(femer)
                                    .addComponent(mashkull))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numriTelefonit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(komunaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rruga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numriDeres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kati, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pershkrimi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prapa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveKlientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearKlientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteKlientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shtoTerapine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveKlientiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveKlientiButtonActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        if (!emri.getText().equals("") && !mbiemri.getText().equals("") && !numriTelefonit.getText().equals("")) {
            int row = tabela.getSelectedRow();
            if (row == -1) {
                Klienti k = new Klienti();
                try {
                    k.setEmri(emri.getText());
                    k.setMbiemri(mbiemri.getText());
                    k.setDataLindjes(dataLindjes.getDate());
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                if (femer.isSelected()) {
                    k.setGjinia('F');
                } else if (mashkull.isSelected()) {
                    k.setGjinia('M');
                } else {
                    JOptionPane.showMessageDialog(this, "Nuk keni zgjedhur gjini");
                }

                try {
                    k.setNrTelefonit(numriTelefonit.getText());
                    Komuna ko = (Komuna) komunaCB.getSelectedItem();
                    k.setKomunaID(ko);
                    k.setEmriRruges(rruga.getText());
                    k.setNumriHyrjes(Integer.parseInt(numriDeres.getText()));
                    k.setKati(Integer.parseInt(kati.getText()));
                    k.setPershkrimi(pershkrimi.getText());
                    try {
                        kr.create(k);
                    } catch (FarmaciaException fe) {
                        JOptionPane.showMessageDialog(this, fe.getMessage());
                    }
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                Terapia t = new Terapia();
                t.setKlientiID(k);
                try {
                    tr.create(t);
                } catch (FarmaciaException ex) {
                    Logger.getLogger(RegjistroKlientin.class.getName()).log(Level.SEVERE, null, ex);
                }
                Object[] ob = {"Po", "Jo"};
                int i = JOptionPane.showOptionDialog(this,
                        "A dëshironi te shtoni terapine ?", "Terapia",
                        JOptionPane.OK_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                System.out.println("" + i);
                if (i == 0) {
                    tf.klientiCB.setSelectedItem(k);
                    panel.add(tf);
                    tf.setVisible(true);
                    BasicInternalFrameUI bi;
                    bi = (BasicInternalFrameUI) tf.getUI();
                    bi.setNorthPane(null);
                    label.setVisible(true);
                }

            } else {
                Klienti k = ktm.getKlienti(row);
                try {
                    k.setEmri(emri.getText());
                    k.setMbiemri(mbiemri.getText());
                    k.setDataLindjes(dataLindjes.getDate());
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                if (femer.isSelected()) {
                    k.setGjinia('F');
                } else {
                    k.setGjinia('M');
                }
                try {
                    k.setNrTelefonit(numriTelefonit.getText());
                    Komuna ko = (Komuna) komunaCB.getSelectedItem();
                    k.setKomunaID(ko);
                    k.setEmriRruges(rruga.getText());
                    k.setNumriHyrjes(Integer.parseInt(numriDeres.getText()));
                    k.setKati(Integer.parseInt(kati.getText()));
                    k.setPershkrimi(pershkrimi.getText());
                    kr.edit(k);
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
            clear();
            loadTable();

        } else {
            JOptionPane.showMessageDialog(this, "Ju lutem plotesoni fushat obligative");
        }
    }//GEN-LAST:event_saveKlientiButtonActionPerformed

    private void femerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femerActionPerformed

    private void mashkullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mashkullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mashkullActionPerformed

    private void deleteKlientiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteKlientiButtonActionPerformed
        // TODO add your handling code here:
        int row = tabela.getSelectedRow();
        if (row != -1) {
            Klienti k = ktm.getKlienti(row);
            List<Terapia> listaTerapive = k.getTerapiaList();
            if (listaTerapive.isEmpty()) {
                Object[] ob = {"Po", "Jo"};
                int i = JOptionPane.showOptionDialog(this,
                        "A dëshironi ta fshini ?", "Fshirja",
                        JOptionPane.OK_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                System.out.println("" + i);
                if (i == 0) {
                    kr.delete(k);
                    loadTable();
                }
            } else {
                Object[] ob = {"Po", "Jo"};
                int i = JOptionPane.showOptionDialog(this,
                        "Ekzistojne terapi qe i takojne ketij klienti.Me fshrijen e klientit do fshihen edhe terapite"
                        + ".Deshironi t'i fshini?", "Fshirja",
                        JOptionPane.OK_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                System.out.println("" + i);
                if (i == 0) {

                    for (int j = 0; j < listaTerapive.size(); j++) {

                        tr.deleteTerapia(listaTerapive.get(j));
                    }
                    kr.delete(k);
                    loadTable();

                }
            }

            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Nuk ke selektuar asgje!");
        }
    }//GEN-LAST:event_deleteKlientiButtonActionPerformed

    private void clearKlientiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearKlientiButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearKlientiButtonActionPerformed

    private void emriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emriActionPerformed

    private void prapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prapaActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.dashboard();
        this.setVisible(false);
        tf.dispose();
        clear();
    }//GEN-LAST:event_prapaActionPerformed

    public void clear() {
        tabela.clearSelection();
        emri.setText("");
        mbiemri.setText("");
        numriTelefonit.setText("");
        rruga.setText("");
        komunaCB.setSelectedItem(null);
        komunaCB.repaint();
        numriDeres.setText("");
        kati.setText("");
        pershkrimi.setText("");

    }
    private void komunaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komunaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komunaCBActionPerformed

    private void shtoTerapineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shtoTerapineActionPerformed
        // TODO add your handling code here:
        int row = tabela.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Nuk ke selektuar asnje furnizues!");
            return;
        }
        Klienti k = ktm.getKlienti(row);
        
        tf.klientiCB.setSelectedItem(k);
        panel.add(tf);
        tf.setVisible(true);
        BasicInternalFrameUI bi;
        bi = (BasicInternalFrameUI) tf.getUI();
        bi.setNorthPane(null);   
        label.setVisible(true);
    }//GEN-LAST:event_shtoTerapineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearKlientiButton;
    private com.toedter.calendar.JDateChooser dataLindjes;
    private javax.swing.JButton deleteKlientiButton;
    private javax.swing.JTextField emri;
    private javax.swing.JRadioButton femer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kati;
    private javax.swing.JComboBox<Komuna> komunaCB;
    private javax.swing.JLabel label;
    private javax.swing.JRadioButton mashkull;
    private javax.swing.JTextField mbiemri;
    private javax.swing.JTextField numriDeres;
    private javax.swing.JTextField numriTelefonit;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField pershkrimi;
    private javax.swing.JButton prapa;
    private javax.swing.JTextField rruga;
    private javax.swing.JButton saveKlientiButton;
    private javax.swing.JButton shtoTerapine;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
