/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BLL.Perdoruesit;
import DAL.FarmaciaException;
import DAL.PerdoruesitRepository;
import gui.models.PerdoruesitTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ASUS
 */
public class RegjistroPerdoruesin extends javax.swing.JInternalFrame {

    PerdoruesitRepository pr = new PerdoruesitRepository();
    PerdoruesitTableModel ptm;

    /**
     * Creates new form PerdoruesiForm
     */
    public RegjistroPerdoruesin() {
        initComponents();
        loadTable();
        tabelaSelectedIndexChange();

    }

    public void loadTable() {
        List<Perdoruesit> list = pr.findAll();
        ptm = new PerdoruesitTableModel(list);
        tabela.setModel(ptm);
        ptm.fireTableDataChanged();

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Perdoruesit p = ptm.getPerdoruesi(selectedIndex);
                    emri.setText(p.getEmriPerdoruesit());
                    fjalekalimi.setText(p.getFjalekalimi());
                    perserit.setText(p.getFjalekalimi());
                    niveliCB.setSelectedItem(p.getNiveliPerdorimit());

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        emri = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fjalekalimi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        perserit = new javax.swing.JTextField();
        savePerdoruesitButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        fshijPerdoruesitButton = new javax.swing.JButton();
        clearPerdoruesitButton = new javax.swing.JButton();
        niveliCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Emri Perdoruesit:");

        jLabel15.setText("Fjalekalimi:");

        jLabel14.setText("Perserit Fjalekalimin:");

        savePerdoruesitButton.setText("Ruaj");
        savePerdoruesitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePerdoruesitButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Niveli i perdorimit:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        fshijPerdoruesitButton.setText("Fshij");
        fshijPerdoruesitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fshijPerdoruesitButtonActionPerformed(evt);
            }
        });

        clearPerdoruesitButton.setText("Pastro");
        clearPerdoruesitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPerdoruesitButtonActionPerformed(evt);
            }
        });

        niveliCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Farmaciste", "Teknik i Farmacise" }));
        niveliCB.setSelectedIndex(-1);

        jButton1.setText("Prapa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(fjalekalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clearPerdoruesitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(perserit, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(niveliCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(savePerdoruesitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(fshijPerdoruesitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fjalekalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perserit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niveliCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savePerdoruesitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fshijPerdoruesitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearPerdoruesitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savePerdoruesitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePerdoruesitButtonActionPerformed
        // TODO add your handling code here:
        if (!emri.getText().trim().equals("") && !fjalekalimi.getText().trim().equals("") && !perserit.getText().trim().equals("") && niveliCB.getSelectedItem() != null) {
            int row = tabela.getSelectedRow();
            if(row == -1){
            Perdoruesit p = new Perdoruesit();
            try {
                p.setEmriPerdoruesit(emri.getText());
            } catch (FarmaciaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            if (!fjalekalimi.getText().equals(perserit.getText())) {
                JOptionPane.showMessageDialog(this, "Fjalekalimet ndryshojne.Ju lutem provoni perseri.");
                return;
            }
            try {
                p.setFjalekalimi(fjalekalimi.getText());
                p.setNiveliPerdorimit((String) niveliCB.getSelectedItem());
                try {
                    pr.create(p);
                } catch (FarmaciaException fe) {
                    JOptionPane.showMessageDialog(this, fe.getMessage());
                }
            } catch (FarmaciaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            }else {
                Perdoruesit p = ptm.getPerdoruesi(row);
                try {
                p.setEmriPerdoruesit(emri.getText());
            } catch (FarmaciaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            if (!fjalekalimi.getText().equals(perserit.getText())) {
                JOptionPane.showMessageDialog(this, "Fjalekalimet ndryshojne.Ju lutem provoni perseri.");
                return;
            }
            try {
                p.setFjalekalimi(fjalekalimi.getText());
                p.setNiveliPerdorimit((String) niveliCB.getSelectedItem());
                pr.edit(p);
            } catch (FarmaciaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
                
            }
            loadTable();
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Ju lutem plotesoni fushat obligative");
        }



    }//GEN-LAST:event_savePerdoruesitButtonActionPerformed

    private void fshijPerdoruesitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fshijPerdoruesitButtonActionPerformed
        // TODO add your handling code here:
        int row = tabela.getSelectedRow();
        if (row != -1) {
            Object[] ob = {"Po", "Jo"};
            int i = JOptionPane.showOptionDialog(this,
                    "A dëshironi ta fshini ?", "Fshirja",
                    JOptionPane.OK_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            System.out.println("" + i);
            if (i == 0) {
                Perdoruesit p = ptm.getPerdoruesi(row);
                pr.delete(p);
                loadTable();

            }
            clear();
            loadTable();

        } else {
            JOptionPane.showMessageDialog(this, "Nuk ke selektuar asgje!");
        }
    }//GEN-LAST:event_fshijPerdoruesitButtonActionPerformed

    private void clearPerdoruesitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPerdoruesitButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearPerdoruesitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Home h = new Home();
        h.dashboard();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void clear() {
        emri.setText("");
        fjalekalimi.setText("");
        perserit.setText("");
        niveliCB.setSelectedItem(null);
        niveliCB.repaint();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearPerdoruesitButton;
    private javax.swing.JTextField emri;
    private javax.swing.JTextField fjalekalimi;
    private javax.swing.JButton fshijPerdoruesitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> niveliCB;
    private javax.swing.JTextField perserit;
    private javax.swing.JButton savePerdoruesitButton;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
