/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BLL.Furnizuesi;
import BLL.Klienti;
import BLL.Komuna;
import DAL.FarmaciaException;
import DAL.FurnizuesiRepository;
import DAL.KomunaInterface;
import DAL.KomunaRepository;
import gui.models.FurnizuesiTableModel;
import gui.models.KlientiTableModel;
import gui.models.KomunaComboboxModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ASUS
 */
public class RegjistroFurnizuesin extends javax.swing.JInternalFrame {

    FurnizuesiRepository fr = new FurnizuesiRepository();
    FurnizuesiTableModel ftm;
    
    KomunaInterface kir = new KomunaRepository();
    KomunaComboboxModel kcm;
    
    ShtoProduktetEFurnizuesit spf = new ShtoProduktetEFurnizuesit();
    
    

    /**
     * Creates new form FurnizuesiForm
     */
    public RegjistroFurnizuesin() {
        initComponents();
        loadTable();
        loadCombobox();
        tabelaSelectedIndexChange();
        label.setVisible(false);
    }
    
    public void loadCombobox(){
        try {
            List<Komuna> list = kir.findAll();
            kcm = new KomunaComboboxModel(list);
            komunaCB.setModel(kcm);
            komunaCB.repaint();

        } catch (FarmaciaException se) {
            JOptionPane.showMessageDialog(this, se.getMessage());

        }
    }

    public void loadTable() {
        List<Furnizuesi> list = fr.findAll();
        ftm = new FurnizuesiTableModel(list);
        tabela.setModel(ftm);
        ftm.fireTableDataChanged();

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Furnizuesi f = ftm.getFurnizuesi(selectedIndex);
                    
                    emri.setText(f.getEmriFurnizuesit() + "");
                    komunaCB.setSelectedItem(f.getKomunaID());
                    komunaCB.repaint();
                    numriTel.setText(f.getNumriTelefonit());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        emri = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        numriTel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        saveFurnizuesiButton = new javax.swing.JButton();
        pastroFurnizuesiButton = new javax.swing.JButton();
        fshijFurnizuesiButton1 = new javax.swing.JButton();
        prapaButton = new javax.swing.JButton();
        komunaCB = new javax.swing.JComboBox<>();
        shtoProdukte = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1160, 710));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Emri Furnizuesit:");

        jLabel15.setText("Komuna:");

        jLabel14.setText("Numri Telefonit:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        saveFurnizuesiButton.setBackground(new java.awt.Color(16, 141, 25));
        saveFurnizuesiButton.setForeground(new java.awt.Color(255, 255, 255));
        saveFurnizuesiButton.setText("Ruaj");
        saveFurnizuesiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFurnizuesiButtonActionPerformed(evt);
            }
        });

        pastroFurnizuesiButton.setBackground(new java.awt.Color(16, 141, 25));
        pastroFurnizuesiButton.setForeground(new java.awt.Color(255, 255, 255));
        pastroFurnizuesiButton.setText("Pastro");
        pastroFurnizuesiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastroFurnizuesiButtonActionPerformed(evt);
            }
        });

        fshijFurnizuesiButton1.setBackground(new java.awt.Color(16, 141, 25));
        fshijFurnizuesiButton1.setForeground(new java.awt.Color(255, 255, 255));
        fshijFurnizuesiButton1.setText("Fshij");
        fshijFurnizuesiButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fshijFurnizuesiButton1ActionPerformed(evt);
            }
        });

        prapaButton.setText("Prapa");
        prapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prapaButtonActionPerformed(evt);
            }
        });

        shtoProdukte.setBackground(new java.awt.Color(16, 141, 25));
        shtoProdukte.setForeground(new java.awt.Color(255, 255, 255));
        shtoProdukte.setText("Shto produkte");
        shtoProdukte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shtoProdukteActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setText("Produktet per furnizuesin:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emri)
                                    .addComponent(komunaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(saveFurnizuesiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fshijFurnizuesiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pastroFurnizuesiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numriTel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prapaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shtoProdukte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prapaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(komunaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numriTel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(saveFurnizuesiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fshijFurnizuesiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pastroFurnizuesiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(shtoProdukte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE)))))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveFurnizuesiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFurnizuesiButtonActionPerformed
        // TODO add your handling code here:
        if (!emri.getText().trim().equals("")) {
            int row = tabela.getSelectedRow();
           if (row == -1) {
                Furnizuesi f = new Furnizuesi();
                try{
                f.setEmriFurnizuesit(emri.getText());
                Komuna k = (Komuna) komunaCB.getSelectedItem();
                f.setKomunaID(k);
                //f.setKomuna((String) komuna.getSelectedItem());
                f.setNumriTelefonit(numriTel.getText());
                try {
                    fr.create(f);
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                }catch(FarmaciaException ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            } else {
                Furnizuesi f = ftm.getFurnizuesi(row);
                try{
                f.setEmriFurnizuesit(emri.getText());
                Komuna k = (Komuna) komunaCB.getSelectedItem();
                f.setKomunaID(k);
                f.setNumriTelefonit(numriTel.getText());
                fr.edit(f);
                }catch(FarmaciaException ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());                    
                }
                
                spf.furnizuesiCB.repaint();
           }
            clear();
            loadTable();
           
        } else {
            JOptionPane.showMessageDialog(this, "Ju lutem plotesoni fushat obligative");
        }
    }//GEN-LAST:event_saveFurnizuesiButtonActionPerformed

    private void pastroFurnizuesiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastroFurnizuesiButtonActionPerformed
        // TODO add your handling code here:
        clear();
        
    }//GEN-LAST:event_pastroFurnizuesiButtonActionPerformed

    private void fshijFurnizuesiButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fshijFurnizuesiButton1ActionPerformed
        // TODO add your handling code here:
         int row = tabela.getSelectedRow();
        if (row != -1) {
            Object[] ob = {"Po", "Jo"};
            int i = JOptionPane.showOptionDialog(this,
                    "A dëshironi ta fshini ?", "Fshirja",
                    JOptionPane.OK_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            System.out.println("" + i);
            if (i == 0) {
                Furnizuesi f = ftm.getFurnizuesi(row);
                fr.delete(f);
                loadTable();
                
            }
            clear();
            
        } else {
            JOptionPane.showMessageDialog(this, "Nuk ke selektuar asgje!");
        }
    }//GEN-LAST:event_fshijFurnizuesiButton1ActionPerformed

    private void prapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prapaButtonActionPerformed
        // TODO add your handling code here:
         Home h = new Home();
        h.dashboard();
        this.setVisible(false);
        spf.dispose();
        clear();
    }//GEN-LAST:event_prapaButtonActionPerformed

    private void shtoProdukteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shtoProdukteActionPerformed
        // TODO add your handling code here:
        
        
        int row = tabela.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Nuk ke selektuar asnje furnizues!");
            return;
        }
        Furnizuesi f = ftm.getFurnizuesi(row);
        
        spf.furnizuesiCB.setSelectedItem(f);
        panel.add(spf);
        spf.setVisible(true);
        BasicInternalFrameUI bi;
        bi = (BasicInternalFrameUI) spf.getUI();
        bi.setNorthPane(null);   
        label.setVisible(true);
        
        
        
    }//GEN-LAST:event_shtoProdukteActionPerformed

    public void clear() {
        tabela.clearSelection();
        emri.setText("");
        komunaCB.setSelectedItem(null);
        komunaCB.repaint();
        numriTel.setText("");
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emri;
    private javax.swing.JButton fshijFurnizuesiButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Komuna> komunaCB;
    private javax.swing.JLabel label;
    private javax.swing.JTextField numriTel;
    private javax.swing.JPanel panel;
    private javax.swing.JButton pastroFurnizuesiButton;
    private javax.swing.JButton prapaButton;
    private javax.swing.JButton saveFurnizuesiButton;
    private javax.swing.JButton shtoProdukte;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
