/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BLL.Furnizuesi;
import BLL.ProduktetEFurnizuesit;
import BLL.Produkti;
import DAL.FarmaciaException;
import DAL.FurnizuesiRepository;
import DAL.ProduktetEFurnizuesitRepository;
import DAL.ProduktiRepository;
import gui.models.FurnizuesiComboBoxModel;
import gui.models.ProduktetEFurnizuesitTableModel;
import gui.models.ProduktiComboBoxModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Auron
 */
public class ShtoProduktetEFurnizuesit extends javax.swing.JInternalFrame {
    
    ProduktetEFurnizuesitRepository fer = new ProduktetEFurnizuesitRepository();
    
    FurnizuesiRepository fr = new FurnizuesiRepository();
    FurnizuesiComboBoxModel fcb;
    
    ProduktiRepository pr = new ProduktiRepository();
    ProduktiComboBoxModel pcb;
    
    ProduktetEFurnizuesitTableModel pftm;
    /**
     * Creates new form ShtoProduktetEFurnizuesit
     */
    public ShtoProduktetEFurnizuesit() {
        initComponents();
        loadProduktiCombobox();
        loadFurnizuesiCombobox();
        loadTable();
    }
    
     public void loadProduktiCombobox() {
         List<Produkti> list = pr.findAll();
         pcb = new ProduktiComboBoxModel(list);
         produktiCB.setModel(pcb);
         produktiCB.repaint();
    }
     
     public void loadFurnizuesiCombobox(){
         List<Furnizuesi> list = fr.findAll();
         fcb = new FurnizuesiComboBoxModel(list);
         furnizuesiCB.setModel(fcb);
         furnizuesiCB.repaint();
     }
     
     public void loadTable() {
        List<ProduktetEFurnizuesit> list = fer.findAll();
        pftm = new ProduktetEFurnizuesitTableModel(list);
        tabela.setModel(pftm);
        pftm.fireTableDataChanged();
        
    }
     
     private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {           
                    ProduktetEFurnizuesit pf = pftm.getProduktetEFurnizuesit(selectedIndex);
                    furnizuesiCB.setSelectedItem(pf.getFurnizuesiID());
                    furnizuesiCB.repaint();
                    produktiCB.setSelectedItem(pf.getProduktiID());
                    produktiCB.repaint();
                                       
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        furnizuesiCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        produktiCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(658, 493));

        jLabel1.setText("Furnizuesi");

        jLabel2.setText("Produkti");

        jButton1.setText("Shto produktin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(furnizuesiCB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(201, 201, 201))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(produktiCB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(furnizuesiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produktiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (furnizuesiCB.getSelectedItem() != null && produktiCB.getSelectedItem() != null) {
            int row = tabela.getSelectedRow();
            if (row == -1) {
                ProduktetEFurnizuesit pf = new ProduktetEFurnizuesit();
                pf.setFurnizuesiID((Furnizuesi) furnizuesiCB.getSelectedItem());
                pf.setProduktiID((Produkti) produktiCB.getSelectedItem());
                
                try {
                    fer.create(pf);
                } catch (FarmaciaException ex) {
                    Logger.getLogger(ShtoProduktetEFurnizuesit.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else {
                ProduktetEFurnizuesit pf = pftm.getProduktetEFurnizuesit(row);
                pf.setFurnizuesiID((Furnizuesi) furnizuesiCB.getSelectedItem());
                pf.setProduktiID((Produkti) produktiCB.getSelectedItem());
                
                try {
                    fer.edit(pf);
                } catch (FarmaciaException ex) {
                    Logger.getLogger(ShtoProduktetEFurnizuesit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            loadTable();

        } else {
            JOptionPane.showMessageDialog(this, "Ju lutem zgjedhni produktin dhe furnizuesin");
        }
//        ProduktetEFurnizuesit pf = new ProduktetEFurnizuesit();
//        pf.setFurnizuesiID((Furnizuesi) furnizuesiCB.getSelectedItem());
//        pf.setProduktiID((Produkti) produktiCB.getSelectedItem());
//        try {
//            fer.create(pf);
//        } catch (FarmaciaException ex) {
//            Logger.getLogger(ShtoProduktetEFurnizuesit.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<Furnizuesi> furnizuesiCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Produkti> produktiCB;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
