/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BLL.Klienti;
import BLL.ProduktetETerapise;
import BLL.Produkti;
import BLL.Terapia;
import DAL.FarmaciaException;
import DAL.KlientiRepository;
import DAL.ProduktetETerapiseRepository;
import DAL.ProduktiInterface;
import DAL.ProduktiRepository;
import DAL.TerapiaRepository;
import gui.models.KlientiComboBoxModel;
import gui.models.ProduktiComboBoxModel;
import gui.models.TerapiaKlientitTableModel;
import gui.models.TerapiaTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Auron
 */
public class TerapiaFinal extends javax.swing.JInternalFrame {

    ProduktiInterface pir = new ProduktiRepository();
    ProduktiComboBoxModel pcb;

    KlientiRepository kr = new KlientiRepository();
    KlientiComboBoxModel kcb;
    TerapiaTableModel ttm;
    TerapiaRepository tr = new TerapiaRepository();
    Terapia t = new Terapia();

    ProduktetETerapiseRepository ptr = new ProduktetETerapiseRepository();

    /**
     * Creates new form TerapiaFinal
     */
    public TerapiaFinal() {
        initComponents();
        loadProduktiCombobox();
        loadKlientiCombobox();
        tabelaSelectedIndexChange();

        loadTable();

    }

    public void loadProduktiCombobox() {
        try {
            List<Produkti> list = pir.findAll();
            pcb = new ProduktiComboBoxModel(list);
            produktiCB.setModel(pcb);
            produktiCB.repaint();

        } catch (FarmaciaException se) {
            JOptionPane.showMessageDialog(this, se.getMessage());

        }
    }

    public void loadKlientiCombobox() {
        List<Klienti> list = kr.findAll();
        kcb = new KlientiComboBoxModel((list));
        klientiCB.setModel(kcb);
        klientiCB.repaint();

    }

    public void loadTable() {
//        Klienti k = (Klienti) klientiCB.getSelectedItem();
//        if (k != null) {
//            List<Terapia> terapite = tr.findTerapiaKlientit(k.getKlientiID());
//            List<ProduktetETerapise> list = null;
//            for (int i = 0; i < terapite.size(); i++) {
//                List<ProduktetETerapise> temp = terapite.get(i).getProduktetETerapiseList();
//                for (int j = 0; j < temp.size(); j++) {
//                    list.add(temp.get(i));
//                }
//            }
        List<ProduktetETerapise> list = ptr.findAll();
        ttm = new TerapiaTableModel(list);
        tabela.setModel(ttm);
        ttm.fireTableDataChanged();
//            for (int i = 0; i < terapite.size(); i++) {
//                System.out.println(terapite.get(i));
//            }
//        }
//        

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    ProduktetETerapise pt = ttm.getProduktetETerapise(selectedIndex);
                    Terapia t = pt.getTerapiaID();
                    klientiCB.setSelectedItem(t.getKlientiID());
                    klientiCB.repaint();
                    produktiCB.setSelectedItem(pt.getProduktiID());
                    produktiCB.repaint();
                    doza.setText(pt.getDoza() + "");
                    ditore.setText(pt.getDitore() + "");
                    kohezgjatja.setText(t.getKohezgjatja() + "");

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        produktiCB = new javax.swing.JComboBox<>();
        doza = new javax.swing.JTextField();
        ditore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        kohezgjatja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        klientiCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(778, 337));

        jLabel1.setText("Terapia per klientin:");

        ditore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ditoreActionPerformed(evt);
            }
        });

        jLabel2.setText("Doza");

        jLabel3.setText("Sa here ne dite:");

        jButton1.setText("Shto produktin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel4.setText("Kohezgjatja e terapise(ne dite):");

        jLabel5.setText("Produktet e terapise:");

        jLabel6.setText("Zgjedh produktin:");

        jButton2.setText("Fshij");

        jButton3.setText("Fresko tabelen:");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(produktiCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(klientiCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kohezgjatja, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(doza, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ditore, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(3, 3, 3)
                        .addComponent(jButton2))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(klientiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(produktiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kohezgjatja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ditore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ditoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ditoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ditoreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!(produktiCB.getSelectedItem() == null) && check(kohezgjatja.getText()) && check(doza.getText()) && check(ditore.getText())) {
            int row = tabela.getSelectedRow();
            if (row == -1) {
                Klienti k = (Klienti) klientiCB.getSelectedItem();

                try {
                    t.setKohezgjatja(Integer.parseInt(kohezgjatja.getText()));
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                t.setKlientiID(k);
                try {
                    tr.create(t);
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                ProduktetETerapise pt = new ProduktetETerapise();
                pt.setTerapiaID(t);
                try {
                    pt.setDitore(Integer.parseInt(ditore.getText()));
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                try {
                    pt.setDoza(Integer.parseInt(doza.getText()));
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                pt.setProduktiID((Produkti) produktiCB.getSelectedItem());

                try {
                    ptr.create(pt);
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

            } else {
                ProduktetETerapise pt = ttm.getProduktetETerapise(row);
                Klienti k = (Klienti) klientiCB.getSelectedItem();

                try {
                    t.setKohezgjatja(Integer.parseInt(kohezgjatja.getText()));
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                t.setKlientiID(k);
                try {
                    tr.create(t);
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

                pt.setTerapiaID(t);
                try {
                    pt.setDitore(Integer.parseInt(ditore.getText()));
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                try {
                    pt.setDoza(Integer.parseInt(doza.getText()));
                } catch (FarmaciaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                pt.setProduktiID((Produkti) produktiCB.getSelectedItem());

            }
            loadTable();
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Ju lutem zgjedhni produktin dhe furnizuesin");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    public boolean check(String s) {
        if (s.trim().equals("")) {
            return false;
        }
        return true;
    }

    public void clear() {
        doza.setText("");
        ditore.setText("");
        produktiCB.setSelectedItem(null);
        kohezgjatja.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ditore;
    public javax.swing.JTextField doza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<Klienti> klientiCB;
    public javax.swing.JTextField kohezgjatja;
    private javax.swing.JComboBox<Produkti> produktiCB;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
